### ISSUE TITLE
Illegal instruction

### ISSUE THREAD

**Issue by tropa** [exantech/monero-nodejs-libwallet#31] opened 2019-07-18 10:52 UTC
Hello
I have just insert 

const monero = require('monero-nodejs-libwallet');

in my app and get "Illegal instruction" in console while starting.

**Comment by naughtyfox** [comment] 2019-07-18 12:00
Hi!
Could you please provide us with more information about your system such as OS, architecture, etc?

It looks like you are trying to run addon on wrong cpu arch.

**Comment by tropa** [comment] 2019-07-18 14:52
node -v
v10.16.0

lsb_release -idrc  # distro, version, codename, long release name
Distributor ID: Ubuntu
Description:    Ubuntu 16.04.6 LTS
Release:        16.04
Codename:       xenial

**Comment by tropa** [comment] 2019-07-18 15:14
lscpu
Architecture:          x86_64
CPU op-mode(s):        32-bit, 64-bit
Byte Order:            Little Endian
CPU(s):                24
On-line CPU(s) list:   0-23
Thread(s) per core:    2
Core(s) per socket:    6
Socket(s):             2
NUMA node(s):          2
Vendor ID:             GenuineIntel
CPU family:            6
Model:                 62
Model name:            Intel(R) Xeon(R) CPU E5-2620 v2 @ 2.10GHz
Stepping:              4
CPU MHz:               1201.839
CPU max MHz:           2600.0000
CPU min MHz:           1200.0000
BogoMIPS:              4202.11
Virtualization:        VT-x
L1d cache:             32K
L1i cache:             32K
L2 cache:              256K
L3 cache:              15360K
NUMA node0 CPU(s):     0-5,12-17
NUMA node1 CPU(s):     6-11,18-23
Flags:                 fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush dts acpi mmx fxsr sse sse2 ss ht tm pbe syscall nx pdpe1gb rdtscp lm constant_tsc arch_perfmon pebs bts rep_good nopl xtopology nonstop_tsc aperfmperf eagerfpu pni pclmulqdq dtes64 monitor ds_cpl vmx smx est tm2 ssse3 cx16 xtpr pdcm pcid dca sse4_1 sse4_2 x2apic popcnt tsc_deadline_timer aes xsave avx f16c rdrand lahf_lm epb ibrs ibpb stibp kaiser tpr_shadow vnmi flexpriority ept vpid fsgsbase smep erms xsaveopt dtherm ida arat pln pts

**Comment by tropa** [comment] 2019-07-18 15:15
ALL the nodejs packages are always work corectly...

**Comment by tropa** [comment] 2019-07-18 15:27
I have tried to build it manually but got error like "npm run build
npm ERR! missing script: build"

and here is a log 

0 info it worked if it ends with ok
1 verbose cli [ '/usr/bin/node', '/usr/bin/npm', 'run', 'build' ]
2 info using npm@6.9.0
3 info using node@v10.16.0
4 verbose stack Error: missing script: build
4 verbose stack     at run (/usr/lib/node_modules/npm/lib/run-script.js:155:19)
4 verbose stack     at /usr/lib/node_modules/npm/lib/run-script.js:63:5
4 verbose stack     at /usr/lib/node_modules/npm/node_modules/read-package-json/read-json.js:115:5
4 verbose stack     at /usr/lib/node_modules/npm/node_modules/read-package-json/read-json.js:418:5
4 verbose stack     at checkBinReferences_ (/usr/lib/node_modules/npm/node_modules/read-package-json/read-json.js:373:45)
4 verbose stack     at final (/usr/lib/node_modules/npm/node_modules/read-package-json/read-json.js:416:3)
4 verbose stack     at then (/usr/lib/node_modules/npm/node_modules/read-package-json/read-json.js:160:5)
4 verbose stack     at /usr/lib/node_modules/npm/node_modules/read-package-json/read-json.js:280:12
4 verbose stack     at /usr/lib/node_modules/npm/node_modules/graceful-fs/graceful-fs.js:90:16
4 verbose stack     at FSReqWrap.readFileAfterClose [as oncomplete] (internal/fs/read_file_context.js:53:3)
5 verbose cwd /home/user/www/exchangeapi
6 verbose Linux 4.4.0-130-generic
7 verbose argv "/usr/bin/node" "/usr/bin/npm" "run" "build"
8 verbose node v10.16.0
9 verbose npm  v6.9.0
10 error missing script: build
11 verbose exit [ 1, true ]

**Comment by naughtyfox** [comment] 2019-07-18 16:50
The last errors occurs because you have not `node-pre-gyp` installed.
Try to find `monero.node` file in `npm_modules` directory and provide us with the following command output:
```
$ file monero.node
``` 

For my ubuntu 18.04 with my Core i3 cpu I have the following result:
```
$ file monero.node
monero.node: ELF 64-bit LSB shared object, x86-64, version 1 (GNU/Linux), dynamically linked, BuildID[sha1]=271de769f3cc5b49085617dac149d1d4e3f1bead, not stripped
```

I wanna make sure you have 64-bit library, maybe it's distribution error.

Thank you for collaboration

**Comment by tropa** [comment] 2019-07-18 16:56
I have built it by hands. And now I will try to start my app again...

**Comment by tropa** [comment] 2019-07-18 17:05
> The last error occurs because you have not `node-pre-gyp` installed (since it's dev dependency). You may try to build it by yourself, but building monero ends up with big headache.
> 
> Try to find `monero.node` file in `npm_modules` directory and provide us with the following command output:
> 
> ```
> $ file monero.node
> ```
> 
> For my ubuntu 18.04 with core i3 cpu I have the following result:
> 
> ```
> $ file monero.node
> monero.node: ELF 64-bit LSB shared object, x86-64, version 1 (GNU/Linux), dynamically linked, BuildID[sha1]=271de769f3cc5b49085617dac149d1d4e3f1bead, not stripped
> ```
> 
> I wanna make sure if you have 64-bit library, maybe it's distribution error.
> 
> Thank you for collaboration

There is no monero.node in `npm_modules` directory

**Comment by naughtyfox** [comment] 2019-07-18 17:38
I can see the problem with undefined symbol, I'll make a patch a bit later.

>  There is no monero.node in npm_modules directory
It may be somewhere else, I believe. You can find it as follows:
```$ sudo udpatedb
$ locate monero.node```

I think you'll get to results - one for you've just built and one npm has intalled.

This is a bit strange since my npm downloads correct binary for me...

**Comment by naughtyfox** [comment] 2019-07-18 18:44
> There is no monero.node in npm_modules directory

this is where my `monero.node` resides:
```
$ file node_modules/monero-nodejs-libwallet/lib/binding/monero.node
```

**Comment by tropa** [comment] 2019-07-18 22:18
file node_modules/monero-nodejs-libwallet/lib/binding/monero.node
node_modules/monero-nodejs-libwallet/lib/binding/monero.node: ELF 64-bit LSB shared object, x86-64, version 1 (GNU/Linux), dynamically linked, BuildID[sha1]=6ec40b882aca210d1661736be30d67e59293148e, not stripped

**Comment by naughtyfox** [comment] 2019-07-19 10:29
this is strange... it works on core iX, but not working on xeon. I'll try to find xeon to test it, thank you for feedback

**Comment by naughtyfox** [comment] 2019-07-19 11:07
Core and Xeon, as I can see, differ with instruction sets. Xeon doesn't have `avx2` instructions, this may cause the problem

**Comment by naughtyfox** [comment] 2019-07-22 14:01
@tropa I fixed `undefined symbol` bug, you may try to checkout and build it again.

The `illegal instruction` seems to be our build problem, I'll fix it in a couple of days. 
Thank you for the report

**Comment by naughtyfox** [comment] 2019-07-24 16:57
@tropa I've updated build, it should not require avx2 instructions now, you may try to check it. If the problem persist just open new issue, I'll have a look. 

PS. aes instructions set is still required (you have it)

**Comment by tropa** [comment] 2019-07-25 11:56
Hey. Thanks for the help. I reassembled the library according to the instructions and received the following:

`internal/modules/cjs/loader.js:805
  return process.dlopen(module, path.toNamespacedPath(filename));
                 ^

Error: /home/user/monero-nodejs-libwallet/lib/binding/monero.node: undefined symbol: _ZTIN6google8protobuf7MessageE`

**Comment by tropa** [comment] 2019-07-25 12:05
And I tried to install the library through NPM and got it too - illegal instruction

**Comment by naughtyfox** [comment] 2019-07-26 09:33
okay, reopen issue :)

**Comment by naughtyfox** [comment] 2019-07-26 09:34
> /home/user/monero-nodejs-libwallet/lib/binding/monero.node: undefined symbol: _ZTIN6google8protobuf7MessageE

it seems monero requires protobuf to be installed on the system.

**Comment by naughtyfox** [comment] 2019-07-26 09:37
did you reproduce the error on the same cpu?

**Comment by naughtyfox** [comment] 2019-07-26 10:12
the only Xeon I've found is `Intel(R) Xeon(R) CPU D-1531 @ 2.20GHz` and the addon works on it. will try to figure out

**Comment by naughtyfox** [comment] 2019-07-26 13:04
Could you please upload somewhere core dump?

**Comment by naughtyfox** [comment] 2019-07-26 13:13
this time should work:
```$ elfx86exts node_modules/monero-nodejs-libwallet/lib/binding/monero.node 
MODE64 (call)
CMOV (cmovne)
SSE1 (movaps)
SSE2 (mfence)
AES (aeskeygenassist)
CPU Generation: Westmere
```

please, update the lib and tell if it works or not

**Comment by tropa** [comment] 2019-07-26 20:33
I cannot generate the core dump, dont know how to do it) 
What way should I update the lib? Just npm -i?

**Comment by naughtyfox** [comment] 2019-07-29 10:54
Normally `npm update`. Just make sure you have version `0.3.11` installed.
Just in case you may `rm -rf node_modelus && rm package-lock.json && npm install` which deletes all of installed modules and forgets about previously installed dependency versions

**Comment by tropa** [comment] 2019-07-30 16:47
I updated the package and it starts but...

`monero.openWallet(
    {
        'path': config.xmr.walletPath,
        'password': config.xmr.masterPassword,
        'network': config.xmr.network,
        'daemonAddress': config.xmr.daemonAddress,
    }).then(function(wallet)
    {
        const balance = wallet.balance();
    }).catch((e) => console.log('Failed to open new wallet: ' + e));`

Segmentation fault

**Comment by naughtyfox** [comment] 2019-07-31 10:41
Ok, that's another issue. Please file new bug, I'll close this one

**Closed by naughtyfox** 2019-07-31 10:41 UTC
Labels: bug
